[package]
name = "trin-metrics"
description = "Trin metrics"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
ethportal-api.workspace = true
lazy_static.workspace = true
prometheus_exporter.workspace = true
