{
 "title": "Trin Execution",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Block Processing Section Duration (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(trin_execution_processing_times_sum {instance=~\"local_node\"} [1m])/rate(trin_execution_processing_times_count {instance=~\"local_node\"} [1m])",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "trin_execution_block_height", "legendFormat": "{{section}}" }
   ]
  },
  {
   "title": "Block Processing Total Time Per Section",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "trin_execution_processing_times_sum {instance=~\"local_node\"}",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(trin_execution_block_height [1m])",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Block Execution Operation Count (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "trin_execution_processing_times_count {instance=~\"local_node\"}",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Average Transaction Processing Section Duration (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(trin_execution_transaction_processing_times_sum {instance=~\"local_node\"} [1m])/rate(trin_execution_transaction_processing_times_count {instance=~\"local_node\"} [1m])",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Average Bundle Commit Processing Section Duration (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(trin_execution_bundle_commit_processing_times_sum {instance=~\"local_node\"} [1m])/rate(trin_execution_bundle_commit_processing_times_count {instance=~\"local_node\"} [1m])",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Transaction Processing Total Time Per Section",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "trin_execution_transaction_processing_times_sum {instance=~\"local_node\"} ",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Average Bundle Commit Processing Section Duration (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "trin_execution_bundle_commit_processing_times_sum {instance=~\"local_node\"}",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Transaction Processing Total Time Per Section",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(trin_execution_transaction_processing_times_sum {instance=~\"local_node\"} [1m])",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Transaction Execution Operation Count (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(trin_execution_transaction_processing_times_count {instance=~\"local_node\"} [1m])",
     "legendFormat": "{{section}}"
    }
   ]
  }
 ]
}