[package]
name = "ethportal-peertest"
description = "Testing utilities for trin"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy = { workspace = true, features = ["getrandom"] }
anyhow.workspace = true
discv5.workspace = true
e2store.workspace = true
ethereum_ssz.workspace = true
ethportal-api.workspace = true
futures.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["async-client", "client", "macros", "server"]}
portalnet.workspace = true
portal-bridge.workspace = true
rand.workspace = true
reth-ipc.workspace = true
rpc.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tree_hash.workspace = true
trin.workspace = true
trin-history.workspace = true
trin-state.workspace = true
trin-utils.workspace = true
trin-validation.workspace = true
ureq.workspace = true
url.workspace = true

[target.'cfg(windows)'.dependencies]
uds_windows.workspace = true

[dev-dependencies]
serial_test.workspace = true
