[package]
name = "portalnet"
description = "Core library for Trin."
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
crossbeam-channel = { workspace = true }
delay_map.workspace = true
discv5.workspace = true
ethereum_ssz.workspace = true
ethportal-api.workspace = true
fnv = { workspace = true }
futures.workspace = true
hex.workspace = true
igd-next = { workspace = true }
itertools.workspace = true
lazy_static.workspace = true
leb128 = { workspace = true }
local-ip-address = { workspace = true }
lru = { workspace = true }
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true
smallvec = { workspace = true }
ssz_types.workspace = true
stunclient = { workspace = true }
thiserror.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
tracing.workspace = true
trin-metrics.workspace = true
trin-storage.workspace = true
trin-utils.workspace = true
trin-validation.workspace = true
utp-rs.workspace = true

[target.'cfg(windows)'.dependencies]
uds_windows.workspace = true

[dev-dependencies]
env_logger.workspace = true
quickcheck.workspace = true
rstest.workspace = true
serial_test.workspace = true
tempfile.workspace = true
test-log.workspace = true
tokio-test.workspace = true
tracing-subscriber.workspace = true
