{
 "title": "Trin Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Content Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed Validations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "trin_validation_total{success=\"false\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Successful Validations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "trin_validation_total{success=\"true\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "uTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "uTP Active Streams (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "trin_utp_active_streams{direction=\"inbound\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP Active Streams (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "trin_utp_active_streams{direction=\"outbound\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Data Tx (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{outcome=\"failed data tx\", direction=\"inbound\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Data Tx (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{direction=\"outbound\", outcome=\"failed data tx\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Shutdown (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{direction=\"inbound\", outcome=\"failed shutdown\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Shutdown (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{direction=\"outbound\", outcome=\"failed shutdown\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Connection (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{outcome=\"failed connection\", direction=\"inbound\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Connection (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{direction=\"outbound\", outcome=\"failed connection\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP Outcome: Success (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{direction=\"inbound\", outcome=\"success\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP Outcome: Success (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total{direction=\"outbound\", outcome=\"success\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total Inbound PING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"received\", type=\"ping\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Outbound PING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(protocol) (rate(trin_message_total{direction=\"sent\", type=\"ping\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inbound PONG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"received\", type=\"pong\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Outbound PONG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"sent\", type=\"pong\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Inbound FINDNODES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"received\", type=\"find_nodes\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Outbound FINDNODES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum by(protocol) (rate(trin_message_total{direction=\"sent\", type=\"find_nodes\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inbound NODES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"received\", type=\"nodes\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Outbound NODES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"sent\", type=\"nodes\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Inbound FINDCONTENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"received\", type=\"find_content\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Outbound FINDCONTENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum by(protocol) (rate(trin_message_total{direction=\"sent\", type=\"find_content\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inbound CONTENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sum by(protocol) (rate(trin_message_total{direction=\"received\", type=\"content\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Outbound CONTENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "rate(trin_message_total{direction=\"sent\", type=\"content\"}[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Entry Count",
   "type": "timeseries",
   "description": "total number of storage entries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    { "expr": "trin_entry_count", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Radius Ratio",
   "type": "timeseries",
   "description": "the fraction of the whole data ring covered by the data radius",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    { "expr": "trin_radius_ratio", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Content Storage Usage",
   "type": "timeseries",
   "description": "sum of size of individual content stored, in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "trin_content_storage_usage_bytes",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Storage Usage",
   "type": "timeseries",
   "description": "full on-disk database size, in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "trin_total_storage_usage_bytes", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "timeseries",
   "description": "user-defined limit on storage usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "trin_storage_capacity_bytes", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Storage processing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(trin_storage_process_timer_sum[$__rate_interval])/rate(trin_storage_process_timer_count[$__rate_interval])",
     "legendFormat": "{{protocol}} function: {{function}}"
    }
   ]
  }
 ]
}