{
 "title": "Trin Metricsx",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "protocol", "query": { "query": "label_values(protocol)" } },
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Content Validation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failed Validations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "trin_validation_total {success=\"false\", protocol=~\"$protocol\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Successful Validations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "trin_validation_total {success=\"true\", protocol=~\"$protocol\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "uTP Active Streams (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "trin_utp_active_streams {protocol=~\"$protocol\",instance=~\"$node\", direction=\"inbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP Active Streams (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "trin_utp_active_streams {protocol=~\"$protocol\",instance=~\"$node\", direction=\"outbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Data Tx (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"failed data tx\", instance=~\"$node\", direction=\"inbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Data Tx (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"failed data tx\", instance=~\"$node\", direction=\"outbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Shutdown (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"failed shutdown\", instance=~\"$node\", direction=\"inbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Shutdown (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"failed shutdown\", instance=~\"$node\", direction=\"outbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Connection (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"failed connection\", instance=~\"$node\", direction=\"inbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Utp Outcome: Failed Connection (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"failed connection\", instance=~\"$node\", direction=\"outbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP Outcome: Success (Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"success\", instance=~\"$node\", direction=\"inbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "uTP Outcome: Success (Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "trin_utp_outcome_total {protocol=~\"$protocol\", outcome=\"success\", instance=~\"$node\", direction=\"outbound\"}",
     "legendFormat": "{{instance}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Inbound PING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"ping\", direction=\"received\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Outbound PING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"ping\", direction=\"sent\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Inbound PONG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"pong\", direction=\"received\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Outbound PONG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"pong\", direction=\"sent\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Inbound FINDNODES",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"find_nodes\", direction=\"received\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Outbound FINDNODES",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"find_nodes\", direction=\"sent\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Inbound NODES",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"nodes\", direction=\"received\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Outbound NODES",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"nodes\", direction=\"sent\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Inbound FINDCONTENT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"find_content\", direction=\"received\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Outbound FINDCONTENT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"find_content\", direction=\"sent\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Inbound CONTENT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"content\", direction=\"received\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Outbound CONTENT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "rate(trin_message_total{type=\"content\", direction=\"sent\",instance=~\"$node\",protocol=~\"$protocol\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Entry Count",
     "type": "timeseries",
     "description": "total number of storage entries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "trin_entry_count{protocol=~\"$protocol\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Radius Ratio",
     "type": "timeseries",
     "description": "the fraction of the whole data ring covered by the data radius",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "trin_radius_ratio {protocol=~\"$protocol\", instance =~ \"$node\"}",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Content Storage Usage",
     "type": "timeseries",
     "description": "sum of size of individual content stored, in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "trin_content_storage_usage_bytes{protocol =~ \"$protocol\", instance =~\"$node\"}",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Total Storage Usage",
     "type": "timeseries",
     "description": "full on-disk database size, in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "trin_total_storage_usage_bytes {protocol =~ \"$protocol\", instance =~\"$node\"}",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    },
    {
     "title": "Storage Capacity",
     "type": "timeseries",
     "description": "user-defined limit on storage usage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "trin_storage_capacity_bytes{protocol =~ \"$protocol\", instance =~\"$node\"}",
       "legendFormat": "{{instance}}-{{protocol}}"
      }
     ]
    }
   ]
  }
 ]
}