name: CI

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          sudo apt update
          sudo apt install -y sudo
          sudo apt install -y git curl
          sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs
          sudo npm install -g conventional-changelog-conventionalcommits
          sudo npm install -g commitlint@latest
          sudo npm install -g @commitlint/config-conventional
          sudo echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
      - name: Validate current commit (last commit) with commitlint
        run: sudo npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        run: sudo npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
